auth_type: basic
board:
    id: 2
    name: STAR board
    type: simple
epic:
    name: ""
    link: ""
installation: Cloud
issue:
    fields:
        custom:
            - name: Design
              key: customfield_10030
              schema:
                datatype: array
                items: design.field.name
            - name: Vulnerability
              key: customfield_10033
              schema:
                datatype: any
            - name: Sprint
              key: customfield_10020
              schema:
                datatype: array
                items: json
            - name: Flagged
              key: customfield_10021
              schema:
                datatype: array
                items: option
            - name: Story point estimate
              key: customfield_10016
              schema:
                datatype: number
            - name: Issue color
              key: customfield_10017
              schema:
                datatype: string
            - name: Rank
              key: customfield_10019
              schema:
                datatype: any
            - name: Start date
              key: customfield_10015
              schema:
                datatype: date
            - name: Development
              key: customfield_10000
              schema:
                datatype: any
            - name: Team
              key: customfield_10001
              schema:
                datatype: team
    types:
        - id: "10007"
          name: Task
          handle: Task
          subtask: false
        - id: "10008"
          name: Epic
          handle: Epic
          subtask: false
        - id: "10009"
          name: Subtask
          handle: Subtask
          subtask: true
        - id: "10010"
          name: Bug
          handle: Bug
          subtask: false
login: kieran.ohara@irkb.me
project:
    key: STAR
    type: next-gen
server: https://irkb-me.atlassian.net
timezone: Europe/London
