[tools]
node = "lts"

# NPM/IDE
"npm:markdownlint-cli" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yaml-language-server" = "latest"

# NPM/MCP
"npm:@1mcp/agent" = "latest"
"npm:@fredrika/mcp-mochi" = "latest"
"npm:@mauricio.wolff/mcp-obsidian" = "latest"
"npm:@playwright/mcp" = "latest"
"npm:@softeria/ms-365-mcp-server" = "latest"
"npm:@xeroapi/xero-mcp-server" = "latest"
"npm:mcp-remote" = "latest"
"npm:omnifocus-mcp" = "latest"

python = "3.11"
uv = "latest"
"pipx:ansible-core" = "2.17.2"
"pipx:httpie" = "3.2.3"
"pipx:yamllint" = "1.35.1"

[settings]
experimental = true

env_file = '.env'

legacy_version_file = true
asdf_compat = false

python.uv_venv_auto = true

idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true
